os: osx
osx_image: xcode10.2
script:
  - xcodebuild -project PaymentSDK/PaymentSDK.xcodeproj -scheme "PaymentSDK" -destination "platform=iOS Simulator,name=iPhone 7" clean test
  - xcodebuild -workspace PaymentSDK/PaymentSDK.xcworkspace -scheme "UIHostApp" -destination "platform=iOS Simulator,name=iPhone 7" clean test
before_install:
  - gem install cocoapods --pre
  - cd PaymentSDK && pod install --repo-update
  - cd ..


